from selecao import Selecao
from grupo import Grupo
from partida import Partida


grupo_a = Grupo("A")
mexico = Selecao("México", 10, 0, "América do Norte")
africa_do_sul = Selecao("África do Sul", 54, 0, "África")
coreia = Selecao("Coréia do Sul", 32, 0, "Ásia")
tchequia = Selecao("Tchéquia", 48, 0, "Europa")
grupo_a.add_selecao(mexico)
grupo_a.add_selecao(africa_do_sul)
grupo_a.add_selecao(coreia)
grupo_a.add_selecao(tchequia)
partida_a1 = Partida(mexico, africa_do_sul)
partida_a1.jogar(2, 0)
partida_a2 = Partida(coreia, tchequia)
partida_a2.jogar(2, 1)
partida_a3 = Partida(tchequia, africa_do_sul)
partida_a3.jogar(1, 1)
partida_a4 = Partida(mexico, coreia)
partida_a4.jogar(1, 0)
partida_a5 = Partida(africa_do_sul, coreia)
partida_a5.jogar(1, 0)
partida_a6 = Partida(tchequia, mexico)
partida_a6.jogar(0, 3)

grupo_b = Grupo("B")
canada = Selecao("Canadá", 30, 0, "América do Norte")
bosnia = Selecao("Bósnia", 61, 0, "Europa")
catar = Selecao("Catar", 59, 0, "Ásia")
suica = Selecao("Suíça", 14, 0, "Europa")
grupo_b.add_selecao(canada)
grupo_b.add_selecao(bosnia)
grupo_b.add_selecao(catar)
grupo_b.add_selecao(suica)
partida_b1 = Partida(canada, bosnia)
partida_b1.jogar(1, 1)
partida_b2 = Partida(catar, suica)
partida_b2.jogar(1, 1)
partida_b3 = Partida(suica, bosnia)
partida_b3.jogar(4, 1)
partida_b4 = Partida(canada, catar)
partida_b4.jogar(6, 0)
partida_b5 = Partida(suica, canada)
partida_b5.jogar(2, 1)
partida_b6 = Partida(bosnia, catar)
partida_b6.jogar(3, 1)


grupo_c = Grupo("C")
brasil = Selecao("Brasil", 5, 5, "América do Sul")
marrocos = Selecao("Marrocos", 6, 0, "África")
haiti = Selecao("Haiti", 88, 0, "América Central")
escocia = Selecao("Escócia", 42, 0, "Europa")
grupo_c.add_selecao(brasil)
grupo_c.add_selecao(marrocos)
grupo_c.add_selecao(haiti)
grupo_c.add_selecao(escocia)
partida_c1 = Partida(brasil, marrocos)
partida_c1.jogar(1, 1)
partida_c2 = Partida(haiti, escocia)
partida_c2.jogar(0, 1)
partida_c3 = Partida(escocia, marrocos)
partida_c3.jogar(0, 1)
partida_c4 = Partida(brasil, haiti)
partida_c4.jogar(3, 0)
partida_c5 = Partida(marrocos, haiti)
partida_c5.jogar(4, 2)
partida_c6 = Partida(escocia, brasil)
partida_c6.jogar(0, 3)

grupo_d = Grupo("D")
eua = Selecao("Estados Unidos", 16, 0, "América do Norte")
paraguai = Selecao("Paraguai", 34, 0, "América do Sul")
australia = Selecao("Austrália", 28, 0, "Oceania")
turquia = Selecao("Turquia", 27, 0, "Europa")
grupo_d.add_selecao(eua)
grupo_d.add_selecao(paraguai)
grupo_d.add_selecao(australia)
grupo_d.add_selecao(turquia)
partida_d1 = Partida(eua, paraguai)
partida_d1.jogar(4, 1)
partida_d2 = Partida(australia, turquia)
partida_d2.jogar(2, 0)
partida_d3 = Partida(eua, australia)
partida_d3.jogar(2, 0)
partida_d4 = Partida(turquia, paraguai)
partida_d4.jogar(0, 1)
partida_d5 = Partida(turquia, eua)
partida_d5.jogar(3, 2)
partida_d6 = Partida(paraguai, australia)
partida_d6.jogar(0, 0)


argentina = Selecao("Argentina", 2, 3, "América do Sul")


print(grupo_a)
print(mexico)
print(africa_do_sul)
print(coreia)
print(tchequia)

print(grupo_b)
print(canada)
print(bosnia)
print(catar)
print(suica)

print(grupo_c)
print(brasil)
print(marrocos)
print(haiti)
print(escocia)

print(grupo_d)
print(eua)
print(paraguai)
print(australia)
print(turquia)