from selecao import Selecao
from grupo import Grupo
from partida import Partida


grupo_a = Grupo("A")
mexico = Selecao("México", 10, 0, "América do Norte")
africa_do_sul = Selecao("África do Sul", 54, 0, "África")
coreia = Selecao("Coréia do Sul", 32, 0, "Ásia")
tchequia = Selecao("Tchéquia", 48, 0, "Europa")
grupo_a.add_selecao(mexico)
grupo_a.add_selecao(africa_do_sul)
grupo_a.add_selecao(coreia)
grupo_a.add_selecao(tchequia)
partida_a1 = Partida(mexico, africa_do_sul)
partida_a1.jogar(2, 0)
partida_a2 = Partida(coreia, tchequia)
partida_a2.jogar(2, 1)
partida_a3 = Partida(tchequia, africa_do_sul)
partida_a3.jogar(1, 1)
partida_a4 = Partida(mexico, coreia)
partida_a4.jogar(1, 0)
partida_a5 = Partida(africa_do_sul, coreia)
partida_a5.jogar(1, 0)
partida_a6 = Partida(tchequia, mexico)
partida_a6.jogar(0, 3)

grupo_b = Grupo("B")
canada = Selecao("Canadá", 30, 0, "América do Norte")
bosnia = Selecao("Bósnia", 61, 0, "Europa")
catar = Selecao("Catar", 59, 0, "Ásia")
suica = Selecao("Suíça", 14, 0, "Europa")
grupo_b.add_selecao(canada)
grupo_b.add_selecao(bosnia)
grupo_b.add_selecao(catar)
grupo_b.add_selecao(suica)
partida_b1 = Partida(canada, bosnia)
partida_b1.jogar(1, 1)
partida_b2 = Partida(catar, suica)
partida_b2.jogar(1, 1)
partida_b3 = Partida(suica, bosnia)
partida_b3.jogar(4, 1)
partida_b4 = Partida(canada, catar)
partida_b4.jogar(6, 0)
partida_b5 = Partida(suica, canada)
partida_b5.jogar(2, 1)
partida_b6 = Partida(bosnia, catar)
partida_b6.jogar(3, 1)


grupo_c = Grupo("C")
brasil = Selecao("Brasil", 5, 5, "América do Sul")
marrocos = Selecao("Marrocos", 6, 0, "África")
haiti = Selecao("Haiti", 88, 0, "América Central")
escocia = Selecao("Escócia", 42, 0, "Europa")
grupo_c.add_selecao(brasil)
grupo_c.add_selecao(marrocos)
grupo_c.add_selecao(haiti)
grupo_c.add_selecao(escocia)
partida_c1 = Partida(brasil, marrocos)
partida_c1.jogar(1, 1)
partida_c2 = Partida(haiti, escocia)
partida_c2.jogar(0, 1)
partida_c3 = Partida(escocia, marrocos)
partida_c3.jogar(0, 1)
partida_c4 = Partida(brasil, haiti)
partida_c4.jogar(3, 0)
partida_c5 = Partida(marrocos, haiti)
partida_c5.jogar(4, 2)
partida_c6 = Partida(escocia, brasil)
partida_c6.jogar(0, 3)

grupo_d = Grupo("D")
eua = Selecao("Estados Unidos", 16, 0, "América do Norte")
paraguai = Selecao("Paraguai", 34, 0, "América do Sul")
australia = Selecao("Austrália", 28, 0, "Oceania")
turquia = Selecao("Turquia", 27, 0, "Europa")
grupo_d.add_selecao(eua)
grupo_d.add_selecao(paraguai)
grupo_d.add_selecao(australia)
grupo_d.add_selecao(turquia)
partida_d1 = Partida(eua, paraguai)
partida_d1.jogar(4, 1)
partida_d2 = Partida(australia, turquia)
partida_d2.jogar(2, 0)
partida_d3 = Partida(eua, australia)
partida_d3.jogar(2, 0)
partida_d4 = Partida(turquia, paraguai)
partida_d4.jogar(0, 1)
partida_d5 = Partida(turquia, eua)
partida_d5.jogar(3, 2)
partida_d6 = Partida(paraguai, australia)
partida_d6.jogar(0, 0)

grupo_e = Grupo("E")
alemanha = Selecao("Alemanha", 12, 4, "Europa")
curacao = Selecao("Curaçao", 82, 0, "América Central")
costa_marfim = Selecao("Costa do Marfim", 31, 0, "África")
equador = Selecao("Equador", 25, 0, "América do Sul")
grupo_e.add_selecao(alemanha)
grupo_e.add_selecao(curacao)
grupo_e.add_selecao(costa_marfim)
grupo_e.add_selecao(equador)
partida_e1 = Partida(alemanha, curacao)
partida_e1.jogar(7, 1)
partida_e2 = Partida(costa_marfim, equador)
partida_e2.jogar(1, 0)
partida_e3 = Partida(alemanha, costa_marfim)
partida_e3.jogar(2, 1)
partida_e4 = Partida(equador, curacao)
partida_e4.jogar(0, 0)
partida_e5 = Partida(equador, alemanha)
partida_e5.jogar(2, 1)
partida_e6 = Partida(curacao, costa_marfim)
partida_e6.jogar(0, 2)

grupo_f = Grupo("F")
holanda = Selecao("Holanda", 9, 0, "Europa")
japao = Selecao("Japão", 17, 0, "Ásia")
suecia = Selecao("Suécia", 37, 0, "Europa")
tunisia = Selecao("Tunísia", 57, 0, "Ásia")
grupo_f.add_selecao(holanda)
grupo_f.add_selecao(japao)
grupo_f.add_selecao(suecia)
grupo_f.add_selecao(tunisia)
partida_f1 = Partida(holanda, japao)
partida_f1.jogar(2, 2)
partida_f2 = Partida(suecia, tunisia)
partida_f2.jogar(5, 1)
partida_f3 = Partida(holanda, suecia)
partida_f3.jogar(5, 1)
partida_f4 = Partida(tunisia, japao)
partida_f4.jogar(0, 4)
partida_f5 = Partida(tunisia, holanda)
partida_f5.jogar(1, 3)
partida_f6 = Partida(japao, suecia)
partida_f6.jogar(1, 1)

grupo_g = Grupo("G")
belgica = Selecao("Bélgica", 8, 0, "Europa")
egito = Selecao("Egito", 24, 0, "África")
ira = Selecao("Irã", 22, 0, "Ásia")
nova_zelandia = Selecao("Nova Zelândia", 86, 0, "Oceania")
grupo_g.add_selecao(belgica)
grupo_g.add_selecao(egito)
grupo_g.add_selecao(ira)
grupo_g.add_selecao(nova_zelandia)
partida_g1 = Partida(belgica, egito)
partida_g1.jogar(1, 1)
partida_g2 = Partida(ira, nova_zelandia)
partida_g2.jogar(2, 2)
partida_g3 = Partida(belgica, ira)
partida_g3.jogar(0, 0)
partida_g4 = Partida(nova_zelandia, egito)
partida_g4.jogar(1, 3)
partida_g5 = Partida(nova_zelandia, belgica)
partida_g5.jogar(1, 5)
partida_g6 = Partida(egito, ira)
partida_g6.jogar(1, 1)

grupo_h = Grupo("H")
espanha = Selecao("Espanha", 1, 1, "Europa")
cabo_verde = Selecao("Cabo Verde", 64, 0, "África")
arabia = Selecao("Arábia Saudita", 58, 0, "Ásia")
uruguai = Selecao("Uruguai", 20, 2, "América do Sul")
grupo_h.add_selecao(espanha)
grupo_h.add_selecao(cabo_verde)
grupo_h.add_selecao(arabia)
grupo_h.add_selecao(uruguai)
partida_h1 = Partida(espanha, cabo_verde)
partida_h1.jogar(0, 0)
partida_h2 = Partida(arabia, uruguai)
partida_h2.jogar(1, 1)
partida_h3 = Partida(espanha, arabia)
partida_h3.jogar(4, 0)
partida_h4 = Partida(uruguai, cabo_verde)
partida_h4.jogar(2, 2)
partida_h5 = Partida(uruguai, espanha)
partida_h5.jogar(0, 1)
partida_h6 = Partida(cabo_verde, arabia)
partida_h6.jogar(0, 0)

grupo_i = Grupo("I")
franca = Selecao("França", 3, 2, "Europa")
senegal = Selecao("Senegal", 18, 0, "África")
iraque = Selecao("Iraque", 63, 0, "Ásia")
noruega = Selecao("Noruega", 19, 0, "Europa")
grupo_i.add_selecao(franca)
grupo_i.add_selecao(senegal)
grupo_i.add_selecao(iraque)
grupo_i.add_selecao(noruega)
partida_i1 = Partida(franca, senegal)
partida_i1.jogar(3, 1)
partida_i2 = Partida(iraque, noruega)
partida_i2.jogar(1, 4)
partida_i3 = Partida(franca, iraque)
partida_i3.jogar(3, 0)
partida_i4 = Partida(noruega, senegal)
partida_i4.jogar(3, 2)
partida_i5 = Partida(noruega, franca)
partida_i5.jogar(1, 4)
partida_i6 = Partida(senegal, iraque)
partida_i6.jogar(5, 0)

grupo_j = Grupo("J")
argentina = Selecao("Argentina", 2, 3, "América do Sul")
argelia = Selecao("Argélia", 29, 0, "África")
austria = Selecao("Áustria", 23, 0, "Europa")
jordania = Selecao("Jordânia", 73, 0, "Ásia")
grupo_j.add_selecao(argentina)
grupo_j.add_selecao(argelia)
grupo_j.add_selecao(austria)
grupo_j.add_selecao(jordania)
partida_j1 = Partida(argentina, argelia)
partida_j1.jogar(3, 0)
partida_j2 = Partida(austria, jordania)
partida_j2.jogar(3, 1)
partida_j3 = Partida(argentina, austria)
partida_j3.jogar(2, 0)
partida_j4 = Partida(jordania, argelia)
partida_j4.jogar(1, 2)
partida_j5 = Partida(jordania, argentina)
partida_j5.jogar(1, 3)
partida_j6 = Partida(argelia, austria)
partida_j6.jogar(3, 3)

grupo_k = Grupo("K")
portugal = Selecao("Portugal", 7, 0, "Europa")
congo = Selecao("Congo", 41, 0, "África")
uzbequistao = Selecao("Uzbequistão", 60, 0, "Ásia")
colombia = Selecao("Colômbia", 11, 0, "América do Sul")
grupo_k.add_selecao(portugal)
grupo_k.add_selecao(congo)
grupo_k.add_selecao(uzbequistao)
grupo_k.add_selecao(colombia)
partida_k1 = Partida(portugal, congo)
partida_k1.jogar(1, 1)
partida_k2 = Partida(uzbequistao, colombia)
partida_k2.jogar(1, 3)
partida_k3 = Partida(portugal, uzbequistao)
partida_k3.jogar(5, 0)
partida_k4 = Partida(colombia, congo)
partida_k4.jogar(1, 0)
partida_k5 = Partida(colombia, portugal)
partida_k5.jogar(0, 0)
partida_k6 = Partida(congo, uzbequistao)
partida_k6.jogar(3, 1)

grupo_l = Grupo("L")
inglaterra = Selecao("Inglaterra", 4, 1, "Europa")
croacia = Selecao("Croácia", 13, 0, "Europa")
gana = Selecao("Gana", 65, 0, "África")
panama = Selecao("Panamá", 44, 0, "América Central")
grupo_l.add_selecao(inglaterra)
grupo_l.add_selecao(croacia)
grupo_l.add_selecao(gana)
grupo_l.add_selecao(panama)
partida_l1 = Partida(inglaterra, croacia)
partida_l1.jogar(4, 2)
partida_l2 = Partida(gana, panama)
partida_l2.jogar(1, 0)
partida_l3 = Partida(inglaterra, gana)
partida_l3.jogar(0, 0)
partida_l4 = Partida(panama, croacia)
partida_l4.jogar(0, 1)
partida_l5 = Partida(panama, inglaterra)
partida_l5.jogar(0, 2)
partida_l6 = Partida(croacia, gana)
partida_l6.jogar(2, 1)


print(grupo_a)
print(mexico)
print(africa_do_sul)
print(coreia)
print(tchequia)

print(grupo_b)
print(canada)
print(bosnia)
print(catar)
print(suica)

print(grupo_c)
print(brasil)
print(marrocos)
print(haiti)
print(escocia)

print(grupo_d)
print(eua)
print(paraguai)
print(australia)
print(turquia)

print(grupo_e)
print(alemanha)
print(curacao)
print(costa_marfim)
print(equador)

print(grupo_f)
print(holanda)
print(japao)
print(suecia)
print(tunisia)

print(grupo_g)
print(belgica)
print(egito)
print(ira)
print(nova_zelandia)

print(grupo_h)
print(espanha)
print(cabo_verde)
print(arabia)
print(uruguai)

print(grupo_i)
print(franca)
print(senegal)
print(iraque)
print(noruega)

print(grupo_j)
print(argentina)
print(argelia)
print(austria)
print(jordania)

print(grupo_k)
print(portugal)
print(congo)
print(uzbequistao)
print(colombia)

print(grupo_l)
print(inglaterra)
print(croacia)
print(gana)
print(panama)